# $FreeBSD$

PORTNAME=	uh
PORTVERSION=	2.0.2
CATEGORIES=	x11-toolkits rubygems
MASTER_SITES=	RG

MAINTAINER=	tj+freebsd_ports@a13.fr
COMMENT=	Xlib ruby toolkit

LICENSE=	BSD3CLAUSE

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_XORG=	x11 xinerama
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
