# $FreeBSD$

PORTNAME=	uh-layout
PORTVERSION=	0.4.3
CATEGORIES=	x11-wm rubygems
MASTER_SITES=	RG

MAINTAINER=	tj+freebsd_ports@a13.fr
COMMENT=	basic layout for uh-wm

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
